sudo: required

language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - npm install -g bats

jobs:
  include:
    - script: make test-debian
    - script: make test-alpine
    - script: make test-jdk11
    - stage: publish
      script: echo "publishing...."
      deploy:
        - provider: script
          script: ./publish.sh latest
          on:
            branch: master

        - provider: script
          script: ./publish.sh $TRAVIS_TAG
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v.*$
