version: '2'
services:
  jenkins-swarm:
    image: csanchez/jenkins-swarm-slave
    environment:
      MASTER: http://host.docker.internal:8080
      LABELS: static-slave
      PASSWORD: password
      USERNAME: jenkins.swarm
      FSROOT: /home/jenkins-slave
      EXECUTORS: '2'
      NAME: static-slave
