name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [debian, alpine, jdk11]
    steps:
      - name: Setup BATS
        uses: bats-core/bats-action@2.0.0

      - uses: actions/checkout@v2

      - name: test test-${{ matrix.dist }}
        run: make test-${{ matrix.dist }}

  deploy-tag:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Login to Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy
        run: |-
          TAG="$(echo ${{ github.event.ref }} | sed 's|refs/tags/||g')"
          ./publish.sh $TAG

  deploy-latest:
    needs: test
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Login to Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy
        run: ./publish.sh latest

